### ISSUE TITLE
[1pt] Create app and install basic dependencies - Setup (group task)

### ISSUE THREAD

**Issue by jellywiz** [jellywiz/space-travlers#24]
- Create React App.
- Install [React Redux](https://react-redux.js.org/), [Redux Logger](https://www.npmjs.com/package/redux-logger) and [React Router](https://reactrouter.com/web/guides/quick-start).

**Comment by Davidosky007** [comment]
Hi @jellywiz @emmanuellmhango 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't contain the right information needed which are 

> A link to your Kanban board project 

> And  a note telling the reviewer how many people there are in your team.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by jellywiz** [comment]
@Davidosky007 thank you for your review, the problem is it doesnt let me submit the link to the kanban 
![image](https://user-images.githubusercontent.com/83097009/208454082-f75a3c9b-ce2d-46b2-a88a-2127d0d36d26.png)
Thanks why i sent this link

**Comment by Davidosky007** [comment]
> @Davidosky007 thank you for your review, the problem is it doesnt let me submit the link to the kanban 
> 
> ![image](https://user-images.githubusercontent.com/83097009/208454082-f75a3c9b-ce2d-46b2-a88a-2127d0d36d26.png)
> 
> Thanks why i sent this link

You need to add all information I mentioned in the issue comment and not on your dashboard
