### ISSUE TITLE
Kanban board

### ISSUE THREAD

**Issue by jellywiz** [jellywiz/space-travlers#25]
This is the link to the Kanban project:  [Click Here](https://github.com/users/jellywiz/projects/6)

The team member are: 

1. @jellywiz 
2. @emmanuellmhango

**Comment by gemmen29** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💯 
- Descriptive info ✔️ 

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Required Changes ♻️
- [ ] Kindly adjust the distribution of the tasks in a fairway since this is a group project, Know one team member has (20pt) and the other has (14pt)

| @jellywiz | @emmanuellmhango |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/24703171/208456089-33747628-9ae5-43d7-8d90-6ec439df51ba.png) | ![image](https://user-images.githubusercontent.com/24703171/208456243-9ec9db09-5cc3-4e8e-b32d-e66564ec590c.png) |

- [ ] Kindly remove the tasks of student three from your kanban board as you are a group of two.
![image](https://user-images.githubusercontent.com/24703171/208456915-b5b14a1e-e134-4560-9a4d-5a7370ce5570.png)



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jellywiz** [comment]
Thank you for your feedback

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @jellywiz and @emmanuellmhango,

✔️ Tasks are evenly distributed

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
